name: expense_traker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  fl_chart: ^1.0.0
  google_fonts: ^5.0.0
  pdf: ^3.10.1
  printing: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0  # ✅ أضف هذا السطر هنا

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"  # لون الخلفية
  image: "assets/images/logo.png"
  android: true
  ios: true
  android_gravity: center


flutter:
  uses-material-design: true
